<a href="https://colab.research.google.com/github/celeste-ro/skills-review-pull-requests/blob/main/8_SleepEfficiency_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Libraries**

In [9]:
from pprint import pprint
import pandas as pd
import numpy as np
import pymongo
import json

#Statistic
from scipy import stats

#Machine Learning
import statsmodels.api as sm

#Visualization
import plotly.graph_objects as go
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.cluster import KMeans

ModuleNotFoundError: No module named 'pymongo'

In [ ]:
#pip install pymongo

In [10]:
#CSV to Json
df1 = pd.read_csv('/content/Sleep_Efficiency.csv')
data = df1.to_dict(orient='records')

#json file loading into mongodb
client = pymongo.MongoClient("mongodb+srv://lavanya:Lavan123@guvilavan.5pjwpvl.mongodb.net/?retryWrites=true&w=majority")

db = client['newdb']
col = db['sleep']
col.insert_many(data)

#Collecting data from mongodb and creating dataframe
dbdata = []
for i in col.find({},{"_id": 0}):
  dbdata.append(i)

df = pd.DataFrame(dbdata)
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '/content/Sleep_Efficiency.csv'

In [ ]:
print(df.columns)

In [ ]:
df['Awakenings'].unique()

In [ ]:
df['Alcohol consumption'].unique()

# **DataFrame observation**

Unsupervised [Clustering / Association]

Dependent column

Independent column

Continuous column

Category column

In [ ]:
continuous_columns = ['Age','Sleep duration',
       'Sleep efficiency', 'REM sleep percentage', 'Deep sleep percentage',
       'Light sleep percentage', 'Awakenings', 'Caffeine consumption',
       'Alcohol consumption', 'Exercise frequency']
category_columns = ["Gender","Smoking status",'Bedtime', 'Wakeup time']

#Unsupervised

# **Data cleaning using pandas**

Handling Null Values

Handling Duplicates

Data Type Conversion

Standardizing or Normalizing Data

Handling Text Data

Handling Date and Time Data

Handling Outliers

In [ ]:
df.info()

In [11]:
df.describe()

,ID,Age,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Exercise frequency
count,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,432.000000,427.000000,438.000000,446.000000
mean,226.500000,40.285398,7.465708,0.788916,22.615044,52.823009,24.561947,1.641204,23.653396,1.173516,1.791480
std,130.625419,13.172250,0.866625,0.135237,3.525963,15.654235,15.313665,1.356762,30.202785,1.621377,1.428134
min,1.000000,9.000000,5.000000,0.500000,15.000000,18.000000,7.000000,0.000000,0.000000,0.000000,0.000000
25%,113.750000,29.000000,7.000000,0.697500,20.000000,48.250000,15.000000,1.000000,0.000000,0.000000,0.000000
50%,226.500000,40.000000,7.500000,0.820000,22.000000,58.000000,18.000000,1.000000,25.000000,0.000000,2.000000
75%,339.250000,52.000000,8.000000,0.900000,25.000000,63.000000,32.500000,3.000000,50.000000,2.000000,3.000000
max,452.000000,69.000000,10.000000,0.990000,30.000000,75.000000,63.000000,4.000000,200.000000,5.000000,5.000000

In [12]:
df.isnull().sum()

ID                         0
Age                        0
Gender                     0
Bedtime                    0
Wakeup time                0
Sleep duration             0
Sleep efficiency           0
REM sleep percentage       0
Deep sleep percentage      0
Light sleep percentage     0
Awakenings                20
Caffeine consumption      25
Alcohol consumption       14
Smoking status             0
Exercise frequency         6
dtype: int64

In [13]:
df.set_index('ID', inplace = True)

In [14]:
df.head()

,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
ID,,,,,,,,,,,,,,
1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0
2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0
3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0
4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0
5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0

In [15]:
df.Awakenings.unique()

array([ 0.,  3.,  1.,  2.,  4., nan])

In [16]:
df['Caffeine consumption'].unique()

array([  0.,  50.,  nan,  25.,  75., 200., 100.])

In [17]:
df['Exercise frequency'].unique()

array([ 3.,  1.,  0.,  5.,  2.,  4., nan])

In [18]:
import datetime
df['Bedtime'] = pd.to_datetime(df['Bedtime'])
df['Bedtime'] = df['Bedtime'].dt.strftime('%H.%M')

df['Wakeup time'] = pd.to_datetime(df['Wakeup time'])
df['Wakeup time'] = df['Wakeup time'].dt.strftime('%H.%M')

# Filling missing values with the median
df['Awakenings'].fillna(value=df['Awakenings'].median(),inplace = True)
df['Caffeine consumption'].fillna(value=df['Caffeine consumption'].median(),inplace = True)
df['Alcohol consumption'].fillna(value=df['Alcohol consumption'].median(),inplace = True)
df['Exercise frequency'].fillna(value=df['Exercise frequency'].median(),inplace = True)

/tmp/ipykernel_4758/3267775995.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Awakenings'].fillna(value=df['Awakenings'].median(),inplace = True)
/tmp/ipykernel_4758/3267775995.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Caffeine consumption'].fillna(value=df['Caffeine consumption'].median(),inplace = True)
/tmp/ipykernel_4758/3267775995.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Alcohol consumption'].fillna(value=df['Alcohol consumption'].median(),inplace = True)
/tmp/ipykernel_4758/3267775995.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Exercise frequency'].fillna(value=df['Exercise frequency'].median(),inplace = True)

In [19]:
df.head()

,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
ID,,,,,,,,,,,,,,
1,65,Female,01.00,07.00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0
2,69,Male,02.00,09.00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0
3,40,Female,21.30,05.30,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0
4,40,Female,02.30,08.30,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0
5,57,Male,01.00,09.00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0

In [20]:
df.isnull().sum()

Age                       0
Gender                    0
Bedtime                   0
Wakeup time               0
Sleep duration            0
Sleep efficiency          0
REM sleep percentage      0
Deep sleep percentage     0
Light sleep percentage    0
Awakenings                0
Caffeine consumption      0
Alcohol consumption       0
Smoking status            0
Exercise frequency        0
dtype: int64

# **Hypothesis testing / Statistical analysis**

Continuous - Central Limit Theorem, 1-Tailed Test (one-sample t-test)

Continuous vs. Continuous - Correlation, 2-Tailed Test (two-sample t-test)

Continuous vs. Categorical - ANOVA (Analysis of Variance)

Categorical vs. Categorical - Chi-Square Test

In [21]:
def hypothesisTesting(continuous_columns = [], category_columns = [], sampling_rate = 0.20, sampling_frac=0.05):
  #Central Limit Theorem
  oneContinesColumn_result = {}
  hypothesis_df = pd.DataFrame(columns=df.columns, index=df.columns)
  if continuous_columns:
    samplesize = int(sampling_rate * len(df[continuous_columns[0]]))
    for column in continuous_columns:
      population=df[column].values
      population_mean = population.mean()
      sample_mean=[]
      for i in range(40):
        sample=np.random.choice(population,samplesize)
        sample_mean.append(sample.mean())
      oneContinesColumn_result[column] = {
                                          "Population Mean": population_mean,
                                          "Sample Means": {np.mean(sample_mean)}
                                          }

  #1-Tailed Test
  if continuous_columns:
    samplesize = int(sampling_rate * len(df[continuous_columns[0]]))
    for column in continuous_columns:
      H0_accepted = 0
      H0_rejected = 0
      for i in range(samplesize):
        sample=df[column].sample(frac=sampling_frac)
        t_test,p_value=stats.ttest_1samp(sample,df[column].mean())
        if p_value > 0.5:
          H0_accepted += 1
        else:
          H0_rejected += 1

      if H0_accepted > H0_rejected:
        oneContinesColumn_result[column].update( {
                                            "H0_accepted": H0_accepted,
                                            "H0_rejected": H0_rejected,
                                            "Conclusion": "H0 is accepted, Ha is rejected, There is no significant effect"
                                          } )
      else:
          oneContinesColumn_result[column].update( {
                                              "H0_accepted": H0_accepted,
                                              "H0_rejected": H0_rejected,
                                              "Conclusion": "H0 is rejected, Ha is accepted, There is a significant effect"
                                              } )

  #2-Tailed Test
  for i in range(len(continuous_columns) - 1):
      column_1 = continuous_columns[i]
      for column_2 in continuous_columns[i+1:]:
        H0_accepted = 0
        H0_rejected = 0
        for i in range(20):
          sample1 = df[column_1].sample(frac=sampling_frac)
          sample2 = df[column_2].sample(frac=sampling_frac)
          t_test, p_value = stats.ttest_ind(sample1, sample2)
          if p_value > 0.5:
            H0_accepted += 1
          else:
            H0_rejected += 1

        if H0_accepted > H0_rejected:
          #H0 is accepted, Ha is rejected, There is no significant effect. "H0_accepted": H0_accepted, "H0_rejected": H0_rejected
          hypothesis_df[column_1][column_2] = "H0 is accepted"
          hypothesis_df[column_2][column_1] = "H0 is accepted"
        else:
          #H0 is rejected, Ha is accepted, There is a significant effect. "H0_accepted": H0_accepted, "H0_rejected": H0_rejected
            hypothesis_df[column_1][column_2] = "H0 is rejected"
            hypothesis_df[column_2][column_1] = "H0 is rejected"

  #Chi-Square Test
  if category_columns:
    for i in range(len(category_columns) - 1):
        column_1 = category_columns[i]
        for column_2 in category_columns[i + 1:]:
            data = pd.crosstab(df[column_1], df[column_2])
            observed_values = data.values
            chi2_stat, p_value, _, _ = stats.chi2_contingency(observed_values)

            if p_value > 0.05:
                # H0 is accepted, There is no relationship between two columns we're comparing
                hypothesis_df[column_1][column_2] = "H0 is accepted"
                hypothesis_df[column_2][column_1] = "H0 is accepted"
            else:
                # H0 is rejected, There is a relationship between two columns we're comparing
                hypothesis_df[column_1][column_2] = "H0 is rejected"
                hypothesis_df[column_2][column_1] = "H0 is rejected"

  #ANOVA
  if continuous_columns and category_columns:
    for category_column in category_columns:
      for continuous_column in continuous_columns:
        group = df[category_column].unique()
        data = {}
        for i in group:
          data[i]=df[continuous_column][df[category_column]==i]

        f_value, p_value = stats.f_oneway(*[data[i] for i in group])
        if p_value > 0.05:
            # H0 is accepted, There is no relationship between two columns we're comparing
            hypothesis_df[category_column][continuous_column] = "H0 is accepted"
            hypothesis_df[continuous_column][category_column] = "H0 is accepted"
        else:
            # H0 is rejected, There is a relationship between two columns we're comparing
            hypothesis_df[category_column][continuous_column] = "H0 is rejected"
            hypothesis_df[continuous_column][category_column] = "H0 is rejected"

  return oneContinesColumn_result, hypothesis_df

# Correlation

In [22]:
df.corr()

ValueError: could not convert string to float: 'Female'

# **Result Hypothesis**

In [ ]:
ContinesColumn_result, comperativeColumn_result = hypothesisTesting(continuous_columns , category_columns)

In [ ]:
ContinesColumn_result_df = pd.DataFrame(ContinesColumn_result)
ContinesColumn_result_df

In [ ]:
# Create a heatmap
sns.heatmap(comperativeColumn_result == 'H0 is rejected', annot=True, cmap='coolwarm')
plt.title('Hypothesis Test Results')
plt.show()

In [ ]:
sns.set()
comperativeColumn_result.fillna(3, inplace = True)
comperativeColumn_result.replace({'H0 is accepted': 1, 'H0 is rejected': 0}, inplace=True)
fig = px.imshow(comperativeColumn_result, color_continuous_scale='Viridis',
                title="Correlation Matrix")
fig.show()

# **Data Visualization**

In [ ]:
correlation_matrix = df.corr()
fig = px.imshow(correlation_matrix, color_continuous_scale='Viridis',
                title="Correlation Matrix")
fig.show()

# **Preprocessing**

In [ ]:
df.head()

In [ ]:
df['Gender'] = df['Gender'].replace({'Female': 1, 'Male': 0})
df['Smoking status'] = df['Smoking status'].replace({'Yes': 1, 'No': 0})

In [ ]:
df

# **Machine Learning**

In [ ]:
import statsmodels.api as sm
from sklearn.cluster import KMeans

In [ ]:
# 1 data availability
# 2 separating independent and dependent
# 3 identifying algorithms/Model
# 4 training
# 5 evaluation

In [ ]:
wcss = []
for i in range(1,453):
  model = KMeans(i)
  model.fit(df)
  wcss.append(model.inertia_)

In [ ]:
print(wcss)

In [ ]:
plt.plot(range(1,35), wcss[0:34])
plt.show()

In [ ]:
result = KMeans(25).fit(df)

In [ ]:
identify_cluster = result.fit_predict(df)
df['cluster'] = identify_cluster

In [ ]:
df.cluster.value_counts()

In [ ]:
df

In [ ]:
df2 = df.apply(pd.to_numeric, errors='coerce')

sns.clustermap(df2)

In [ ]:
pd.set_option('display.max_rows',None)
df3 = df2[df2['cluster'] ==9]
df3

In [ ]:
df2.head(10)

# Results

## Exercise Efficiency & Sleep Outcomes

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

url = "https://raw.githubusercontent.com/Lavan1999/Dataset-8_SleepEfficiency_KMeansCluster/main/Sleep_Efficiency.csv"

df = pd.read_csv(url)

df.columns

In [ ]:
plt.figure(figsize=(8, 5))


sns.histplot(df['Sleep efficiency'], bins=15)


plt.title('Distribution of Sleep Efficiency')
plt.xlabel('Sleep Efficiency')
plt.ylabel('Count')


plt.show()

The distribution exercise frequency shows that most participants reported moderate levels of exercise. On the other hand, even less participants reported very low or very high exercise frequency. Thus, most people in the dataset somewhat regularly exercise.

## Distribution of Sleep Efficiency

In [ ]:
plt.figure(figsize=(8, 5))

sns.histplot(df['Sleep efficiency'], bins=15)

plt.title('Distribution of Sleep Efficiency')
plt.xlabel('Sleep Efficiency')
plt.ylabel('Count')

plt.show()

Most participants had fairly high sleep efficiency values, with many observations clustering around higher efficiency ranges. This suggests that the dataset overall includes participants with pretty moderate to good sleep quality.

## Outliers

In [ ]:
plt.figure(figsize=(8, 5))

sns.boxplot(y=df['Sleep efficiency'])

plt.title('Sleep Efficiency Outliers')
plt.ylabel('Sleep Efficiency')

plt.show()

The boxplot shows lower-end outliers in sleep efficiency, meaning a small number of participants experienced significantly poorer sleep quality compared to the rest of the dataset.

## Relationship Between Variables

In [ ]:
plt.figure(figsize=(8, 5))

sns.scatterplot(
    data=df,
    x='Exercise frequency',
    y='Sleep efficiency'
)

plt.title('Exercise Frequency vs Sleep Efficiency')
plt.xlabel('Exercise Frequency')
plt.ylabel('Sleep Efficiency')

plt.show()

The scatterplot suggests a slightly positive correlation between exercise frequency and sleep efficiency. Participants who exercised more frequently tended to have higher sleep efficiency values. Although the relationship is not exactly linear, the trend does support our hypothesis that healthier lifestyle behaviors are associated with better sleep outcomes.